name: Continious Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: housing-predict-service
  IMAGE_TAG: latest

jobs:
  # --- STAGE 1: CONTINUOUS INTEGRATION (CI) ---
  code-quality-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cahce/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: RUn Code linter (Flake 8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run Automated Test
        run: |
          pytest -v
  
  # --- STAGE 2: CONTINUOUS DELIVERY (CD) --- BUILD & PUSH ---
  build-and-ship-to-ecr:
    runs-on: ubuntu-latest
    # CRITICAL: This job will only run if the test stage passes flawlessly!
    needs: code-quality-and-testing

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      
      # Step 1: Authenticate with AWS using our hidden GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # Step 2: Automatically log our remote runner into AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # Step 3: Build the production container image and push it to ECR
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: housing-predict-service
          IMAGE_TAG: latest
        run: |
          # Build the container exactly like we did locally
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # Push the container to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # --- STAGE 3: CONTINUOUS DEPLOYMENT (CD) - SERVER UPDATE ---
  deploy-to-ec2:
    runs-on: ubuntu-latest
    # CRITICAL: Run only after the new image is safely pushed to ECR
    needs: build-and-ship-to-ecr
    steps:
      # Use a verified community tool to handle the complex secure SSH commands seamlessly
      - name: Execute Remote SSH Commands on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_REGION, ECR_REPOSITORY, IMAGE_TAG

          script: |
            # 1. Update system configurations and install AWS CLI inside the server if missing
            sudo apt-get update -y && sudo apt-get install -y unzip

            # 2. Download and install official AWS CLI v2 if 'aws' command doesn't exist
            if ! command -v aws &> /dev/null; then
              echo "AWS CLI not found. Installing official AWS CLI v2..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -q awscliv2.zip
              sudo ./aws/install --update
              rm -rf awscliv2.zip ./aws
            fi

            # Use the AWS CLI on the server to dynamically fetch the account registry URI
            ECR_REGISTRY=$(aws ecr describe-registrie --region $AWS_REGION --query 'registries[0].registryId' --output text).dkr.ecr.$AWS_REGION.amazonaws.com

            # Log in to ECR using variables dynamically
            aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY

            # Pull down the fresh image layer using variables dynamically
            sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            # Stop and remove the old running container cleanly
            sudo docker rm -f live-housing-api || true

            # Spin up the brand-new model container
            sudo docker run -d \
              --name live-housing-api \
              -p 80:80 \
              $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


